# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files /afs/ece.cmu.edu/usr/rohitban/Private/545/pacman_rom/coe_files/tile_rom.coe
add_files /afs/ece.cmu.edu/usr/rohitban/Private/545/pacman_rom/coe_files/palette.coe
add_files /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/coe_files/tile_index.coe
add_files /afs/ece.cmu.edu/usr/rohitban/Private/545/pacman_rom/coe_files/4bytePalette.coe
add_files -quiet /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.runs/tile_rom_synth_1/tile_rom.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.runs/tile_rom_synth_1/tile_rom.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.runs/tilemap_rom_synth_1/tilemap_rom.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.runs/tilemap_rom_synth_1/tilemap_rom.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.runs/palette_4byte_rom_synth_1/palette_4byte_rom.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.runs/palette_4byte_rom_synth_1/palette_4byte_rom.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/synth/full_tile/full_tile.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib -sv {
  /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/pixel_num.sv
  /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/pixel_data.sv
  /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/color_store.sv
  /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/full_tile.sv
  /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/lib.sv
  /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/vga_controller.sv
  /afs/ece.cmu.edu/usr/rohitban/Private/545/video/tilemap/full_tilemap/top.sv
}
read_xdc /afs/ece.cmu.edu/usr/rohitban/Downloads/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/rohitban/Downloads/Nexys4_Master.xdc]

synth_design -top top -part xc7a100tcsg324-3
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
